/* DO NOT EDIT THIS FILE - it is machine generated */
#include <jni.h>
/* Header for class com_android_common_utils_EncryptUtil */

#ifndef _Included_com_android_common_utils_EncryptUtil
#define _Included_com_android_common_utils_EncryptUtil
#ifdef __cplusplus
extern "C" {
#endif
#ifdef __cplusplus
}
#endif
#endif
